import { Router } from 'express';
import { authRoutes } from './auth.routes.js';
import { adminRoutes } from '../../modules/admin/admin.routes.js';
import { boostRoutes } from '../../modules/boosts/boost.routes.js';
import { categoryRoutes } from './category.routes.js';
import { cartRoutes } from '../../modules/cart/cart.routes.js';
import { conversationRoutes } from '../../modules/conversations/conversation.routes.js';
import { healthRoutes } from './health.routes.js';
import { interactionRoutes } from './interaction.routes.js';
import { productRoutes } from './product.routes.js';
import { notificationRoutes } from '../../modules/notifications/notification.routes.js';
import { offerRoutes } from '../../modules/offers/offer.routes.js';
import { orderRoutes } from '../../modules/orders/order.routes.js';
import { paymentRoutes } from '../../modules/payments/payment.routes.js';
import { reportRoutes } from '../../modules/reports/report.routes.js';
import { reviewRoutes } from '../../modules/reviews/review.routes.js';
import { sellerVerificationRoutes } from '../../modules/seller-verification/seller-verification.routes.js';
import { settingRoutes } from '../../modules/settings/setting.routes.js';
import { supportRoutes } from '../../modules/support/support.routes.js';
import { userRoutes } from './user.routes.js';

export const apiRoutes = Router();

apiRoutes.use('/health', healthRoutes);
apiRoutes.use('/auth', authRoutes);
apiRoutes.use('/admin', adminRoutes);
apiRoutes.use('/boosts', boostRoutes);
apiRoutes.use('/categories', categoryRoutes);
apiRoutes.use('/cart', cartRoutes);
apiRoutes.use('/products', productRoutes);
apiRoutes.use('/users', userRoutes);
apiRoutes.use('/conversations', conversationRoutes);
apiRoutes.use('/notifications', notificationRoutes);
apiRoutes.use('/orders', orderRoutes);
apiRoutes.use('/payments', paymentRoutes);
apiRoutes.use('/reports', reportRoutes);
apiRoutes.use('/reviews', reviewRoutes);
apiRoutes.use('/seller-verification', sellerVerificationRoutes);
apiRoutes.use('/settings', settingRoutes);
apiRoutes.use('/support', supportRoutes);
apiRoutes.use('/', offerRoutes);
apiRoutes.use('/', interactionRoutes);
