export const queryKeys = {
  session: ['session'],
  categories: ['categories'],
  products: (filters = {}) => ['products', filters],
  product: (slug) => ['product', slug],
  myProducts: ['products', 'mine'],
  favorites: ['favorites'],
  likes: ['likes'],
  publicUser: (userId) => ['users', userId, 'public'],
  userReviews: (userId) => ['reviews', 'users', userId],
  conversations: ['conversations'],
  conversationList: ['conversations', 'list'],
  conversation: (conversationId) => ['conversations', 'detail', conversationId],
  conversationMessages: (conversationId) => ['conversations', 'messages', conversationId],
  notifications: ['notifications'],
  notificationList: ['notifications', 'list'],
  notificationPages: ['notifications', 'pages'],
  orders: ['orders'],
  orderList: (filters = {}) => ['orders', 'list', filters],
  order: (orderId) => ['orders', 'detail', orderId],
  orderQuote: (input = {}) => ['orders', 'quote', input],
  payments: ['payments'],
  paymentList: (filters = {}) => ['payments', 'list', filters],
  payment: (paymentId) => ['payments', 'detail', paymentId],
  boostPlans: ['boosts', 'plans'],
  boosts: ['boosts'],
  myBoosts: (filters = {}) => ['boosts', 'mine', filters],
  supportTickets: (filters = {}) => ['support', 'tickets', filters],
  supportTicket: (ticketId) => ['support', 'tickets', ticketId],
  sellerVerification: ['seller-verification', 'me'],
}
