export const queryKeys = {
  session: ['session'],
  categories: ['categories'],
  products: (filters = {}) => ['products', filters],
  product: (slug) => ['product', slug],
  myProducts: ['products', 'mine'],
  favorites: ['favorites'],
  likes: ['likes'],
  publicUser: (userId) => ['users', userId, 'public'],
  userReviews: (userId) => ['reviews', 'users', userId],
  conversations: ['conversations'],
  conversationList: ['conversations', 'list'],
  conversation: (conversationId) => ['conversations', 'detail', conversationId],
  conversationMessages: (conversationId) => ['conversations', 'messages', conversationId],
  notifications: ['notifications'],
  notificationList: ['notifications', 'list'],
  notificationPages: ['notifications', 'pages'],
  orders: ['orders'],
  orderList: (filters = {}) => ['orders', 'list', filters],
  order: (orderId) => ['orders', 'detail', orderId],
  orderQuote: (input = {}) => ['orders', 'quote', input],
  payments: ['payments'],
  paymentList: (filters = {}) => ['payments', 'list', filters],
  payment: (paymentId) => ['payments', 'detail', paymentId],
  boostPlans: ['boosts', 'plans'],
  boosts: ['boosts'],
  myBoosts: (filters = {}) => ['boosts', 'mine', filters],
  supportTickets: (filters = {}) => ['support', 'tickets', filters],
  supportTicket: (ticketId) => ['support', 'tickets', ticketId],
  sellerVerification: ['seller-verification', 'me'],
  admin: {
    root: ['admin'],
    dashboard: ['admin', 'dashboard'],
    usersRoot: ['admin', 'users'],
    users: (filters = {}) => ['admin', 'users', filters],
    productsRoot: ['admin', 'products'],
    products: (filters = {}) => ['admin', 'products', filters],
    ordersRoot: ['admin', 'orders'],
    orders: (filters = {}) => ['admin', 'orders', filters],
    paymentsRoot: ['admin', 'payments'],
    payments: (filters = {}) => ['admin', 'payments', filters],
    payoutsRoot: ['admin', 'payouts'],
    payouts: (filters = {}) => ['admin', 'payouts', filters],
    boostsRoot: ['admin', 'boosts'],
    boosts: (filters = {}) => ['admin', 'boosts', filters],
    boostPlansRoot: ['admin', 'boost-plans'],
    boostPlans: (filters = {}) => ['admin', 'boost-plans', filters],
    reportsRoot: ['admin', 'reports'],
    reports: (filters = {}) => ['admin', 'reports', filters],
    reviewsRoot: ['admin', 'reviews'],
    reviews: (filters = {}) => ['admin', 'reviews', filters],
    verificationsRoot: ['admin', 'verifications'],
    verifications: (filters = {}) => ['admin', 'verifications', filters],
    conversationsRoot: ['admin', 'conversations'],
    conversations: (filters = {}) => ['admin', 'conversations', filters],
    supportRoot: ['admin', 'support'],
    support: (filters = {}) => ['admin', 'support', filters],
    categoriesRoot: ['admin', 'categories'],
    categories: (filters = {}) => ['admin', 'categories', filters],
    settings: ['admin', 'settings'],
    logsRoot: ['admin', 'logs'],
    logs: (filters = {}) => ['admin', 'logs', filters],
  },
}
