import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, CreditCard, FileText, Image as ImageIcon, MessageSquare, Truck, UserCheck } from 'lucide-react'
import { useState } from 'react'
import { useParams } from 'react-router-dom'
import { adminApi } from '../../api/admin.js'
import { errorMessage } from '../../api/errors.js'
import AdminConfirmDialog from '../../components/admin/AdminConfirmDialog.jsx'
import AdminPage from '../../components/admin/AdminPage.jsx'
import AdminStatusBadge from '../../components/admin/AdminStatusBadge.jsx'
import { AdminError, AdminLoading } from '../../components/admin/AdminState.jsx'
import Button from '../../components/ui/Button.jsx'
import Card from '../../components/ui/Card.jsx'
import Select from '../../components/ui/Select.jsx'
import Textarea from '../../components/ui/Textarea.jsx'
import { formatAdminDate, formatAdminMoney } from '../../lib/adminFormatters.js'
import { useToast } from '../../lib/toast.jsx'

export default function AdminDisputeDetail() {
  const { id } = useParams(); const queryClient = useQueryClient(); const showToast = useToast()
  const [dialog, setDialog] = useState(false); const [resolution, setResolution] = useState('NO_ACTION'); const [note, setNote] = useState(''); const [refundAmount, setRefundAmount] = useState('')
  const query = useQuery({ queryKey: ['admin', 'disputes', id], queryFn: () => adminApi.disputes.detail(id) })
  const assign = useMutation({ mutationFn: () => adminApi.disputes.assign(id), onSuccess: () => { query.refetch(); showToast('Litige pris en charge.') }, onError: (error) => showToast(errorMessage(error), { type: 'error' }) })
  const resolve = useMutation({ mutationFn: () => adminApi.disputes.resolve(id, { status: resolution === 'NO_ACTION' ? 'REJECTED' : 'RESOLVED', resolution, note: note.trim(), ...(resolution === 'REFUND_PARTIAL' ? { refundAmount } : {}) }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['admin', 'disputes'] }); query.refetch(); setDialog(false); showToast('Décision enregistrée.') }, onError: (error) => showToast(errorMessage(error), { type: 'error' }) })
  if (query.isLoading) return <AdminLoading rows={7} />
  if (query.isError || !query.data) return <AdminError onRetry={query.refetch} message="Ce litige ne peut pas être chargé." />
  const dispute = query.data; const messages = dispute.order?.conversation?.messages || []; const payment = dispute.payment; const delivery = dispute.order?.delivery
  return <AdminPage backTo="/admin/disputes" eyebrow={`Litige · ${dispute.reference}`} title={dispute.order?.product?.title || 'Commande'} description={`Ouvert le ${formatAdminDate(dispute.createdAt)} par ${dispute.openedBy?.fullName || 'un utilisateur'}.`} actions={<AdminStatusBadge status={dispute.status} />}>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="min-w-0 space-y-5">
      <Card className="p-5"><SectionTitle icon={FileText} title="Résumé de la commande" /><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Detail label="Référence" value={dispute.order?.reference} /><Detail label="Statut" value={dispute.order?.status} /><Detail label="Montant total" value={formatAdminMoney(dispute.order?.totalAmount)} /><Detail label="Acheteur" value={dispute.order?.buyer?.fullName} /><Detail label="Vendeur" value={dispute.order?.seller?.fullName} /><Detail label="Ouvert par" value={dispute.openedBy?.fullName} /></dl></Card>
      <Card className="border-red-100 bg-red-50 p-5"><SectionTitle icon={FileText} title="Motif du litige" tone="red" /><p className="mt-3 whitespace-pre-wrap text-sm font-semibold leading-6 text-red-900">{dispute.reason}</p>{dispute.resolutionNote ? <p className="mt-4 border-t border-red-200 pt-3 text-sm font-semibold text-red-900"><strong>Décision :</strong> {dispute.resolutionNote}</p> : null}</Card>
      <Card className="p-5"><SectionTitle icon={CreditCard} title="Paiement et remboursements" />{payment ? <div className="mt-4 space-y-4"><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Detail label="Statut paiement" value={payment.status} /><Detail label="Montant payé" value={formatAdminMoney(payment.amount)} /><Detail label="Fournisseur" value={payment.provider} /><Detail label="Référence interne" value={payment.internalReference} /><Detail label="Transaction fournisseur" value={payment.providerTransactionId} /><Detail label="Payé le" value={formatAdminDate(payment.paidAt)} /></dl><div><p className="text-xs font-black uppercase text-fifow-muted">Remboursements</p>{payment.refunds?.length ? <div className="mt-2 space-y-2">{payment.refunds.map((refund) => <div key={refund.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 p-3 text-sm"><span className="font-bold">{refund.internalReference}</span><span className="font-black">{formatAdminMoney(refund.amount)} · {refund.status}</span></div>)}</div> : <p className="mt-2 text-sm font-semibold text-fifow-muted">Aucun remboursement enregistré.</p>}</div></div> : <p className="mt-3 text-sm font-semibold text-fifow-muted">Aucun paiement associé.</p>}</Card>
      <Card className="p-5"><SectionTitle icon={Truck} title="Livraison et versement vendeur" /><div className="mt-4 grid gap-5 sm:grid-cols-2"><div><Detail label="Livraison" value={delivery?.status || 'Non créée'} /><Detail label="Mode" value={delivery?.mode} /><Detail label="Référence de suivi" value={delivery?.trackingReference} />{delivery?.history?.length ? <div className="mt-3 space-y-2">{delivery.history.map((entry) => <p key={entry.id} className="text-xs font-semibold text-fifow-muted">{entry.toStatus} · {formatAdminDate(entry.createdAt)}</p>)}</div> : null}</div><div><Detail label="Statut versement" value={dispute.order?.payout?.status || 'Non créé'} /><Detail label="Montant vendeur" value={formatAdminMoney(dispute.order?.payout?.amount)} /><Detail label="Disponible le" value={formatAdminDate(dispute.order?.payout?.availableAt)} /></div></div></Card>
      <Card className="p-5"><SectionTitle icon={MessageSquare} title="Conversation liée" />{messages.length ? <div className="mt-4 max-h-[420px] space-y-3 overflow-y-auto pr-1">{messages.map((message) => <div key={message.id} className="rounded-lg bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><span className="text-xs font-black text-fifow-primary">{message.senderId === dispute.order?.buyerId ? 'Acheteur' : message.senderId === dispute.order?.sellerId ? 'Vendeur' : 'Participant'}</span><span className="text-[11px] font-semibold text-fifow-muted">{formatAdminDate(message.createdAt)}</span></div>{message.text ? <p className="mt-2 whitespace-pre-wrap text-sm font-semibold text-fifow-secondary">{message.text}</p> : null}{message.mediaKey ? <a className="mt-2 inline-flex items-center gap-2 text-xs font-black text-fifow-primary hover:underline" href={`/uploads/${message.mediaKey}`} target="_blank" rel="noreferrer"><ImageIcon className="h-4 w-4" /> Voir la pièce jointe</a> : null}</div>)}</div> : <p className="mt-3 text-sm font-semibold text-fifow-muted">Aucun message disponible.</p>}</Card>
      <Card className="p-5"><SectionTitle icon={FileText} title="Historique de la commande" /><div className="mt-4 space-y-3">{(dispute.order?.statusHistory || []).map((entry) => <div key={entry.id} className="rounded-lg bg-slate-50 p-3"><p className="text-sm font-black text-fifow-dark">{entry.toStatus}</p><p className="mt-1 text-xs font-semibold text-fifow-muted">{formatAdminDate(entry.createdAt)}{entry.reason ? ` · ${entry.reason}` : ''}</p></div>)}</div></Card>
    </div><aside className="space-y-4 xl:sticky xl:top-24">{dispute.status === 'OPEN' ? <Button type="button" className="w-full" icon={UserCheck} loading={assign.isPending} onClick={() => assign.mutate()}>Prendre en charge</Button> : null}{!['RESOLVED', 'REJECTED'].includes(dispute.status) ? <Card className="p-5"><h2 className="font-black text-fifow-dark">Décision</h2><Select className="mt-4" value={resolution} onChange={(event) => setResolution(event.target.value)}><option value="NO_ACTION">Rejeter le litige</option><option value="REFUND_FULL">Remboursement total</option><option value="REFUND_PARTIAL">Remboursement partiel</option><option value="RELEASE_PAYOUT">Autoriser le versement vendeur</option></Select>{resolution === 'REFUND_PARTIAL' ? <input className="mt-3 h-11 w-full rounded-lg border border-fifow-border px-3" inputMode="numeric" value={refundAmount} onChange={(event) => setRefundAmount(event.target.value.replace(/\D/g, ''))} placeholder="Montant remboursé" /> : null}<Textarea className="mt-3 min-h-28" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Expliquez la décision au client et au vendeur." /><Button type="button" className="mt-3 w-full" icon={CheckCircle2} disabled={note.trim().length < 3 || (resolution === 'REFUND_PARTIAL' && !refundAmount)} onClick={() => setDialog(true)}>Enregistrer la décision</Button></Card> : <Card className="p-5"><p className="text-sm font-bold text-fifow-secondary">Ce dossier est clôturé. La décision et les montants restent consultables dans l’historique.</p></Card>}</aside></div>
    <AdminConfirmDialog open={dialog} title="Confirmer cette décision" description="Cette décision sera conservée dans l’historique du dossier et communiquée aux personnes concernées." confirmLabel="Confirmer" loading={resolve.isPending} onClose={() => setDialog(false)} onConfirm={() => resolve.mutate()} />
  </AdminPage>
}

function Detail({ label, value }) { return <div><dt className="text-xs font-black uppercase text-fifow-muted">{label}</dt><dd className="mt-1 break-words text-sm font-bold text-fifow-dark">{value || '—'}</dd></div> }
function SectionTitle({ icon: Icon, title, tone = 'default' }) { return <h2 className={`flex items-center gap-2 text-lg font-black ${tone === 'red' ? 'text-red-900' : 'text-fifow-dark'}`}><Icon className="h-5 w-5" />{title}</h2> }
